### ISSUE TITLE
 Constribute mod español CompareItemStats

### ISSUE THREAD

**Issue by T3sl4B0y** [direwolf420/CompareItemStats#5]
Hello. I want to contribute to the translation of CompareItemStats.
I have already done the translation. If you like you can review it. I pass the link of the file
I tried to pass the file but it won't let me pass .Hjson files
Thank you if you see my msg
My Email: Kenger.2blek@gmail.com

[TranslationsSpanish.txt](https://github.com/direwolf420/CompareItemStats/files/13611942/TranslationsSpanish.txt)

**Comment by direwolf420** [comment]
Closed in favor of #6
